### ISSUE TITLE
Missing/incomplete docs

### ISSUE THREAD

**Issue by thislooksfun** [joshwilsonvu/eslint-plugin-solid#27]
This isn't actually a bug, but there wasn't a "docs" issue template. Some of the documentation is incomplete or out of date.

Incomplete:
- https://github.com/joshwilsonvu/eslint-plugin-solid/blob/main/docs/prefer-classlist.md -- missing description for `classnames` key
- https://github.com/joshwilsonvu/eslint-plugin-solid/blob/main/docs/self-closing-comp.md -- bad code formatting in table
- Most keys would benefit from a 'default value' column, especially boolean keys, even if the default value seems obvious

Missing:
- https://github.com/joshwilsonvu/eslint-plugin-solid/blob/main/docs/prefer-show.md

**Comment by joshwilsonvu** [comment]
Thanks for the feedback! I've added descriptions and defaults to all options and updated the options format in the docs.
