### ISSUE TITLE
Upgrade to Eslint 8

### ISSUE THREAD

**Issue by N0tExisting** [joshwilsonvu/eslint-plugin-solid#3]
At the moment this repo is using eslint v7 but a new version of eslint came out.
The plugin works with the new version, but does not officially support nor test v8.
 I might be worth considering dropping support for v6 and instead adding support for v8.

**Comment by joshwilsonvu** [comment]
Good point, addressed in https://github.com/joshwilsonvu/eslint-plugin-solid/releases/tag/v0.2.0. I've upgraded internal use to ESLint 8, and added it to `peerDependencies` and the test suites. No real reason to drop ESLint v6 as long as it's passing tests though, so I've kept those.
